name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Build Docker image
        run: |
          docker build -t golang-ddd-template .
      - name: Login to Heroku
        run: |
          heroku container:login
      - name: Push Docker image to Heroku
        run: |
          heroku container:push web --app golang-ddd-template
      - name: Deploy to Heroku
        run: |
          heroku container:release web --app golang-ddd-template
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
